apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyhello
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: pyhello
  template:
    metadata:
      labels:
        app: pyhello
    spec:
      containers:
      - image: mandjiny89/pyhello:latest
        name: pyhello
        ports:
        - containerPort: 8080
