apiVersion: v1
kind: Pod
metadata:
  name: pyhello
  labels:
    app: pyhello
spec:
  containers:
    - name: pyhello
      image: mandjiny89/pyhello:latest
      ports:
        - containerPort: 8080
